// CITY ACTIONS
export const GET_ALL_CITIES = "GET_ALL_CITIES";
export const UPDATE_FILTERED_CITIES = "UPDATE_FILTERED_CITIES";
// AUTH ACTIONS
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// ITINERARY ACTIONS
export const GET_ITINERARIES = "GET_ITINERARIES";
export const ADD_NEW_ITINERARY = "ADD_NEW_ITINERARY";
// FAVORITES ACTIONS
export const GET_FAVORITES = "GET_FAVORITES";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const CLEAR_FAVORITES = "CLEAR_FAVORITES";
